version: "3.3"

services:
  
  mgr-node-0: &mysql
    image: mysql:${TAG}
    container_name: mgr-node-0
    restart: unless-stopped
    env_file:
      - ./env/base.env
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
      - ${MGR_PORT}
    volumes:
      - ./cnf/mgr-node.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./log/node-0/:/var/log/mysql/
      - mgr-node-0-data:/var/lib/mysql
      - ./init-db-sql/init-master.sh:/docker-entrypoint-initdb.d/1-init-master.sh
    command: [
      "--server-id=${NODE_0_SERVER_ID}",
      "--report_host=${NODE_0_IP}",
      "--loose-loose-group_replication_local_address=${NODE_0_IP}:${MGR_PORT}",
      "--loose-group_replication_group_seeds=${NODE_0_IP}:${MGR_PORT},${NODE_1_IP}:${MGR_PORT},${NODE_2_IP}:${MGR_PORT}",
      "--loose-group_replication_ip_whitelist=${NODE_IP_WHITE_LIST}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      mgr_cluster:
        ipv4_address: ${NODE_0_IP}

  mgr-node-1:
    <<: *mysql
    container_name: mgr-node-1
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    depends_on:
      - mgr-node-0
    volumes:
      - ./cnf/mgr-node.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./log/node-1/:/var/log/mysql/
      - mgr-node-1-data:/var/lib/mysql
#      - ./init-db-sql/init-node.sh:/docker-entrypoint-initdb.d/1-init-node.sh
    command: [
      "--server-id=${NODE_1_SERVER_ID}",
      "--report_host=${NODE_1_IP}",
      "--loose-loose-group_replication_local_address=${NODE_1_IP}:${MGR_PORT}",
      "--loose-group_replication_group_seeds=${NODE_0_IP}:${MGR_PORT},${NODE_1_IP}:${MGR_PORT},${NODE_2_IP}:${MGR_PORT}",
      "--loose-group_replication_ip_whitelist=${NODE_IP_WHITE_LIST}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      mgr_cluster:
        ipv4_address: ${NODE_1_IP}
  
  mgr-node-2:
    <<: *mysql
    container_name: mgr-node-2
    ports:
      - "3308:3306"
    depends_on:
      - mgr-node-0
    volumes:
      - ./cnf/mgr-node.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./log/node-2/:/var/log/mysql/
      - mgr-node-2-data:/var/lib/mysql
    command: [
      "--server-id=${NODE_2_SERVER_ID}",
      "--report_host=${NODE_2_IP}",
      "--loose-loose-group_replication_local_address=${NODE_2_IP}:${MGR_PORT}",
      "--loose-group_replication_group_seeds=${NODE_0_IP}:${MGR_PORT},${NODE_1_IP}:${MGR_PORT},${NODE_2_IP}:${MGR_PORT}",
      "--loose-group_replication_ip_whitelist=${NODE_IP_WHITE_LIST}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      mgr_cluster:
        ipv4_address: ${NODE_2_IP}
    

volumes:
  mgr-node-0-data:
  mgr-node-1-data:
  mgr-node-2-data:

networks:
  mgr_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.29.0.0/16
